version: '3.8'

services:
  chat-app:
    build: .
    container_name: chat-app
    ports:
      - "3000:3000"
    volumes:
      - chat_data:/app/data
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge

volumes:
  chat_data:
